VERSION = '0.0.2'
NAME = 'ultrasequence'
DESCRIPTION = 'An extremely fast file sequencing tool.'
AUTHOR = 'Cody Cuellar'
EMAIL = 'cody.cuellar@gmail.com'
LICENSE = 'MIT'
COPYRIGHT = '©2017 Cody Cuellar'
URL = 'http://github.com/codycuellar/ultrasequence.git'
